cols = ['giniCoefficient', 'PopDensity', 'WhitePerc', 'BlackPerc',
         'NativePerc', 'AsianPerc', 'IslanderPerc', 'OtherRacePerc',
         'TwoOrMoreRacesPerc', 'MedianAge', 'AvgHouseholdIncome', 'incomeTax',
         'costRank', 'groceryCost', 'housingCost', 'utilitiesCost',
         'transportationCost', 'miscCost', 'AverageTemperature',
         'UnemploymentRate', 'UnemploymentRank',
         'votesTrump_percent2020', 'votesBiden_percent',
         'VEP Turnout Rate (Total Ballots Counted)', 'HomicideRate2017(per100k)',
         'TotalHomicides2017', 'TrumpApproval_perc', 'TrumpDisapproval_perc',
         'TrumpnetChangeSinceOffice_perc', 'BachelorsDegreeHolders2018_perc',
         'Age0-18_perc', 'Age19-25_perc','Age26-34_perc', 'Age35-54_perc', 
         'Age55-64_perc', 'Age65+_perc', 'NrLawEnforcementAgencies', 
         'TotalLawEnforcementEmployees_per1000','HealthInsuranceCoverageByEmployer',
       	 'HealthInsuranceCoverageByMedicaid','HealthInsuranceCoverageByMedicare', 
       	 'Uninsured','LifeExpectancyAtBirth_years', 'HealthSpendingperCapita']

rename_cols = {
'giniCoefficient': 'Gini Coefficient',
'PopDensity':'Population Density',
'WhitePerc':'Percentage of White Population',
'BlackPerc':'Percentage of Black Population',
'NativePerc': 'Percentage of Native Population', 
'AsianPerc': 'Percentage of Asian Population',
'IslanderPerc': 'Percentage of Islander Population',
'OtherRacePerc': 'Percentage of Other Race Population',
'TwoOrMoreRacesPerc': 'Percentage of Mixed Race Population',
'MedianAge': 'Median Age',
'AvgHouseholdIncome': 'Avgerage Household Income',
'incomeTax': 'Income Tax Percentage',
'costRank': 'Ranking of Living Costs',
'groceryCost': 'Ranking of Grocery Costs',
'housingCost': 'Ranking of Housing Costs',
'utilitiesCost': 'Ranking of Utilities Costs',
'transportationCost': 'Ranking of Transportation Costs',
'miscCost': 'Ranking of Miscellaneous Costs',
'UnemploymentRate': 'Unemployment Rate', 
'UnemploymentRank': 'Unemployment Rate Rank', 
'votesTrump_percent2020': 'Percentage of Votes for Trump',
'votesBiden_percent':'Percentage of Votes for Biden',
'VEP Turnout Rate (Total Ballots Counted)': 'Voter Turnout 2020', 
'HomicideRate2017(per100k)': 'Homicide Rates Per 100k(2017)', 
'TotalHomicides2017': 'Total Homicides 2017',
'TrumpApproval_perc': 'Trump Approval Rate', 
'TrumpDisapproval_perc':'Trump Disapproval Rate',
'TrumpnetChangeSinceOffice_perc': 'Trump Approval Rate netChange',
'BachelorsDegreeHolders2018_perc': 'Percentage of Bachelors DegreeHolders 2018',
'Age0-18_perc': 'Percentage of Population Age 0-18',
'Age19-25_perc': 'Percentage of Population Age 19-25',
'Age26-34_perc': 'Percentage of Population Age 26-34',
'Age35-54_perc': 'Percentage of Population Age 35-54',
'Age55-64_perc': 'Percentage of Population Age 55-64',
'Age65+_perc': 'Percentage of Population Age 65+',
'NrLawEnforcementAgencies': 'Nr of Law Enforcement Agencies',
'TotalLawEnforcementEmployees_per1000': 'Total Law Enforcement Employees Per 1000K',
'HealthInsuranceCoverageByEmployer': '% of Population with Health Insurance covered by Employer',
'HealthInsuranceCoverageByMedicaid': '% of Population with Health Insurance covered by Medicaid',
'Uninsured': 'Percentage of Uninsured', 
'LifeExpectancyAtBirth_years': 'Life Expectancy At Birth',
'HealthSpendingperCapita': 'Health Spending per Capita'}

#include in state_exploration.py all the current column names
#add this line to webbapp.py line after line 300
#cols = [rename_cols.get(n, n) for n in cols]